only_rules:
  - redundant_objc_attribute
  - implicit_return
  - implicitly_unwrapped_optional
  - generic_type_name
  - force_try
  - force_unwrapping
  - force_cast
  - discouraged_object_literal
  - discouraged_assert
  - discouraged_direct_init
  - convenience_type
  - control_statement
  - conditional_returns_on_newline
  - closure_parameter_position
  - capture_variable
  - class_delegate_protocol
  - closing_brace
  - closure_spacing
  - colon
  - comma
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - operator_usage_whitespace
  - override_in_extension   
  - private_over_fileprivate
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unused_closure_parameter
  - unused_import
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - line_length
  - file_length
  - type_body_length
  - weak_delegate
  - duplicate_enum_cases
  - empty_count
  - deployment_target
  - duplicate_imports
  - empty_string
  - redundant_string_enum_value
  - unused_capture_list
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated

excluded: # paths to ignore during linting.
  - Pods
  - Wait/Generated

colon:
  apply_to_dictionaries: false

indentation: 2

line_length: 180

file_length:
  warning: 800
  error: 1000

type_body_length:
  - 400
  - 500
